[package]
name = "aktors"
version = "0.1.0"
authors = ["insanitybit <insanitybit@gmail.com>"]

[dependencies]
futures = "0.1"
tokio-core = "*"

[dependencies.channel]
git = "https://github.com/stjepang/channel"
rev = "949ce33946d9e4686386ebbbe022b71de9b20950"